; generated by prob2pddl.py problem-28x7-cubic-6.prob
; ############################
; #ROY                       #
; #########################  #
; #                          #
; #  #########################
; #                       ROY#
; ############################
; 
; Figure 1 from Cubic paper https://sections.maa.org/florida/proceedings/2001/friedman.pdf, 6 instead of 10 blocks, stretched low-medium wide.
; R:2 O:2 Y:2 blocks:6 spaces:76
(define (problem problem-28x7-cubic-6)
(:domain puzznic)

    (:objects
        red - pattern
        orange - pattern
        yellow - pattern
        green - pattern
        blue - pattern
        violet - pattern
        pink - pattern
        coal - pattern
        lightblue - pattern
        loc_1_1 - location
        loc_2_1 - location
        loc_3_1 - location
        loc_4_1 - location
        loc_5_1 - location
        loc_6_1 - location
        loc_7_1 - location
        loc_8_1 - location
        loc_9_1 - location
        loc_10_1 - location
        loc_11_1 - location
        loc_12_1 - location
        loc_13_1 - location
        loc_14_1 - location
        loc_15_1 - location
        loc_16_1 - location
        loc_17_1 - location
        loc_18_1 - location
        loc_19_1 - location
        loc_20_1 - location
        loc_21_1 - location
        loc_22_1 - location
        loc_23_1 - location
        loc_24_1 - location
        loc_25_1 - location
        loc_26_1 - location
        loc_27_1 - location
        loc_28_1 - location
        loc_1_2 - location
        loc_2_2 - location
        loc_3_2 - location
        loc_4_2 - location
        loc_5_2 - location
        loc_6_2 - location
        loc_7_2 - location
        loc_8_2 - location
        loc_9_2 - location
        loc_10_2 - location
        loc_11_2 - location
        loc_12_2 - location
        loc_13_2 - location
        loc_14_2 - location
        loc_15_2 - location
        loc_16_2 - location
        loc_17_2 - location
        loc_18_2 - location
        loc_19_2 - location
        loc_20_2 - location
        loc_21_2 - location
        loc_22_2 - location
        loc_23_2 - location
        loc_24_2 - location
        loc_25_2 - location
        loc_26_2 - location
        loc_27_2 - location
        loc_28_2 - location
        loc_1_3 - location
        loc_2_3 - location
        loc_3_3 - location
        loc_4_3 - location
        loc_5_3 - location
        loc_6_3 - location
        loc_7_3 - location
        loc_8_3 - location
        loc_9_3 - location
        loc_10_3 - location
        loc_11_3 - location
        loc_12_3 - location
        loc_13_3 - location
        loc_14_3 - location
        loc_15_3 - location
        loc_16_3 - location
        loc_17_3 - location
        loc_18_3 - location
        loc_19_3 - location
        loc_20_3 - location
        loc_21_3 - location
        loc_22_3 - location
        loc_23_3 - location
        loc_24_3 - location
        loc_25_3 - location
        loc_26_3 - location
        loc_27_3 - location
        loc_28_3 - location
        loc_1_4 - location
        loc_2_4 - location
        loc_3_4 - location
        loc_4_4 - location
        loc_5_4 - location
        loc_6_4 - location
        loc_7_4 - location
        loc_8_4 - location
        loc_9_4 - location
        loc_10_4 - location
        loc_11_4 - location
        loc_12_4 - location
        loc_13_4 - location
        loc_14_4 - location
        loc_15_4 - location
        loc_16_4 - location
        loc_17_4 - location
        loc_18_4 - location
        loc_19_4 - location
        loc_20_4 - location
        loc_21_4 - location
        loc_22_4 - location
        loc_23_4 - location
        loc_24_4 - location
        loc_25_4 - location
        loc_26_4 - location
        loc_27_4 - location
        loc_28_4 - location
        loc_1_5 - location
        loc_2_5 - location
        loc_3_5 - location
        loc_4_5 - location
        loc_5_5 - location
        loc_6_5 - location
        loc_7_5 - location
        loc_8_5 - location
        loc_9_5 - location
        loc_10_5 - location
        loc_11_5 - location
        loc_12_5 - location
        loc_13_5 - location
        loc_14_5 - location
        loc_15_5 - location
        loc_16_5 - location
        loc_17_5 - location
        loc_18_5 - location
        loc_19_5 - location
        loc_20_5 - location
        loc_21_5 - location
        loc_22_5 - location
        loc_23_5 - location
        loc_24_5 - location
        loc_25_5 - location
        loc_26_5 - location
        loc_27_5 - location
        loc_28_5 - location
        loc_1_6 - location
        loc_2_6 - location
        loc_3_6 - location
        loc_4_6 - location
        loc_5_6 - location
        loc_6_6 - location
        loc_7_6 - location
        loc_8_6 - location
        loc_9_6 - location
        loc_10_6 - location
        loc_11_6 - location
        loc_12_6 - location
        loc_13_6 - location
        loc_14_6 - location
        loc_15_6 - location
        loc_16_6 - location
        loc_17_6 - location
        loc_18_6 - location
        loc_19_6 - location
        loc_20_6 - location
        loc_21_6 - location
        loc_22_6 - location
        loc_23_6 - location
        loc_24_6 - location
        loc_25_6 - location
        loc_26_6 - location
        loc_27_6 - location
        loc_28_6 - location
        loc_1_7 - location
        loc_2_7 - location
        loc_3_7 - location
        loc_4_7 - location
        loc_5_7 - location
        loc_6_7 - location
        loc_7_7 - location
        loc_8_7 - location
        loc_9_7 - location
        loc_10_7 - location
        loc_11_7 - location
        loc_12_7 - location
        loc_13_7 - location
        loc_14_7 - location
        loc_15_7 - location
        loc_16_7 - location
        loc_17_7 - location
        loc_18_7 - location
        loc_19_7 - location
        loc_20_7 - location
        loc_21_7 - location
        loc_22_7 - location
        loc_23_7 - location
        loc_24_7 - location
        loc_25_7 - location
        loc_26_7 - location
        loc_27_7 - location
        loc_28_7 - location
)
    (:init
        (= (total-cost) 0)
        (next loc_2_2 loc_3_2 right)
        (next loc_2_2 loc_2_3 up)
        (next loc_3_2 loc_2_2 left)
        (next loc_3_2 loc_4_2 right)
        (next loc_3_2 loc_3_3 up)
        (next loc_4_2 loc_3_2 left)
        (next loc_4_2 loc_5_2 right)
        (next loc_5_2 loc_4_2 left)
        (next loc_5_2 loc_6_2 right)
        (next loc_6_2 loc_5_2 left)
        (next loc_6_2 loc_7_2 right)
        (next loc_7_2 loc_6_2 left)
        (next loc_7_2 loc_8_2 right)
        (next loc_8_2 loc_7_2 left)
        (next loc_8_2 loc_9_2 right)
        (next loc_9_2 loc_8_2 left)
        (next loc_9_2 loc_10_2 right)
        (next loc_10_2 loc_9_2 left)
        (next loc_10_2 loc_11_2 right)
        (next loc_11_2 loc_10_2 left)
        (next loc_11_2 loc_12_2 right)
        (next loc_12_2 loc_11_2 left)
        (next loc_12_2 loc_13_2 right)
        (next loc_13_2 loc_12_2 left)
        (next loc_13_2 loc_14_2 right)
        (next loc_14_2 loc_13_2 left)
        (next loc_14_2 loc_15_2 right)
        (next loc_15_2 loc_14_2 left)
        (next loc_15_2 loc_16_2 right)
        (next loc_16_2 loc_15_2 left)
        (next loc_16_2 loc_17_2 right)
        (next loc_17_2 loc_16_2 left)
        (next loc_17_2 loc_18_2 right)
        (next loc_18_2 loc_17_2 left)
        (next loc_18_2 loc_19_2 right)
        (next loc_19_2 loc_18_2 left)
        (next loc_19_2 loc_20_2 right)
        (next loc_20_2 loc_19_2 left)
        (next loc_20_2 loc_21_2 right)
        (next loc_21_2 loc_20_2 left)
        (next loc_21_2 loc_22_2 right)
        (next loc_22_2 loc_21_2 left)
        (next loc_22_2 loc_23_2 right)
        (next loc_23_2 loc_22_2 left)
        (next loc_23_2 loc_24_2 right)
        (next loc_24_2 loc_23_2 left)
        (next loc_24_2 loc_25_2 right)
        (next loc_25_2 loc_24_2 left)
        (next loc_25_2 loc_26_2 right)
        (next loc_26_2 loc_25_2 left)
        (next loc_26_2 loc_27_2 right)
        (next loc_27_2 loc_26_2 left)
        (next loc_2_3 loc_3_3 right)
        (next loc_2_3 loc_2_4 up)
        (next loc_2_3 loc_2_2 down)
        (next loc_3_3 loc_2_3 left)
        (next loc_3_3 loc_3_4 up)
        (next loc_3_3 loc_3_2 down)
        (next loc_2_4 loc_3_4 right)
        (next loc_2_4 loc_2_3 down)
        (next loc_3_4 loc_2_4 left)
        (next loc_3_4 loc_4_4 right)
        (next loc_3_4 loc_3_3 down)
        (next loc_4_4 loc_3_4 left)
        (next loc_4_4 loc_5_4 right)
        (next loc_5_4 loc_4_4 left)
        (next loc_5_4 loc_6_4 right)
        (next loc_6_4 loc_5_4 left)
        (next loc_6_4 loc_7_4 right)
        (next loc_7_4 loc_6_4 left)
        (next loc_7_4 loc_8_4 right)
        (next loc_8_4 loc_7_4 left)
        (next loc_8_4 loc_9_4 right)
        (next loc_9_4 loc_8_4 left)
        (next loc_9_4 loc_10_4 right)
        (next loc_10_4 loc_9_4 left)
        (next loc_10_4 loc_11_4 right)
        (next loc_11_4 loc_10_4 left)
        (next loc_11_4 loc_12_4 right)
        (next loc_12_4 loc_11_4 left)
        (next loc_12_4 loc_13_4 right)
        (next loc_13_4 loc_12_4 left)
        (next loc_13_4 loc_14_4 right)
        (next loc_14_4 loc_13_4 left)
        (next loc_14_4 loc_15_4 right)
        (next loc_15_4 loc_14_4 left)
        (next loc_15_4 loc_16_4 right)
        (next loc_16_4 loc_15_4 left)
        (next loc_16_4 loc_17_4 right)
        (next loc_17_4 loc_16_4 left)
        (next loc_17_4 loc_18_4 right)
        (next loc_18_4 loc_17_4 left)
        (next loc_18_4 loc_19_4 right)
        (next loc_19_4 loc_18_4 left)
        (next loc_19_4 loc_20_4 right)
        (next loc_20_4 loc_19_4 left)
        (next loc_20_4 loc_21_4 right)
        (next loc_21_4 loc_20_4 left)
        (next loc_21_4 loc_22_4 right)
        (next loc_22_4 loc_21_4 left)
        (next loc_22_4 loc_23_4 right)
        (next loc_23_4 loc_22_4 left)
        (next loc_23_4 loc_24_4 right)
        (next loc_24_4 loc_23_4 left)
        (next loc_24_4 loc_25_4 right)
        (next loc_25_4 loc_24_4 left)
        (next loc_25_4 loc_26_4 right)
        (next loc_26_4 loc_25_4 left)
        (next loc_26_4 loc_27_4 right)
        (next loc_26_4 loc_26_5 up)
        (next loc_27_4 loc_26_4 left)
        (next loc_27_4 loc_27_5 up)
        (next loc_26_5 loc_27_5 right)
        (next loc_26_5 loc_26_6 up)
        (next loc_26_5 loc_26_4 down)
        (next loc_27_5 loc_26_5 left)
        (next loc_27_5 loc_27_6 up)
        (next loc_27_5 loc_27_4 down)
        (next loc_2_6 loc_3_6 right)
        (next loc_3_6 loc_2_6 left)
        (next loc_3_6 loc_4_6 right)
        (next loc_4_6 loc_3_6 left)
        (next loc_4_6 loc_5_6 right)
        (next loc_5_6 loc_4_6 left)
        (next loc_5_6 loc_6_6 right)
        (next loc_6_6 loc_5_6 left)
        (next loc_6_6 loc_7_6 right)
        (next loc_7_6 loc_6_6 left)
        (next loc_7_6 loc_8_6 right)
        (next loc_8_6 loc_7_6 left)
        (next loc_8_6 loc_9_6 right)
        (next loc_9_6 loc_8_6 left)
        (next loc_9_6 loc_10_6 right)
        (next loc_10_6 loc_9_6 left)
        (next loc_10_6 loc_11_6 right)
        (next loc_11_6 loc_10_6 left)
        (next loc_11_6 loc_12_6 right)
        (next loc_12_6 loc_11_6 left)
        (next loc_12_6 loc_13_6 right)
        (next loc_13_6 loc_12_6 left)
        (next loc_13_6 loc_14_6 right)
        (next loc_14_6 loc_13_6 left)
        (next loc_14_6 loc_15_6 right)
        (next loc_15_6 loc_14_6 left)
        (next loc_15_6 loc_16_6 right)
        (next loc_16_6 loc_15_6 left)
        (next loc_16_6 loc_17_6 right)
        (next loc_17_6 loc_16_6 left)
        (next loc_17_6 loc_18_6 right)
        (next loc_18_6 loc_17_6 left)
        (next loc_18_6 loc_19_6 right)
        (next loc_19_6 loc_18_6 left)
        (next loc_19_6 loc_20_6 right)
        (next loc_20_6 loc_19_6 left)
        (next loc_20_6 loc_21_6 right)
        (next loc_21_6 loc_20_6 left)
        (next loc_21_6 loc_22_6 right)
        (next loc_22_6 loc_21_6 left)
        (next loc_22_6 loc_23_6 right)
        (next loc_23_6 loc_22_6 left)
        (next loc_23_6 loc_24_6 right)
        (next loc_24_6 loc_23_6 left)
        (next loc_24_6 loc_25_6 right)
        (next loc_25_6 loc_24_6 left)
        (next loc_25_6 loc_26_6 right)
        (next loc_26_6 loc_25_6 left)
        (next loc_26_6 loc_27_6 right)
        (next loc_26_6 loc_26_5 down)
        (next loc_27_6 loc_26_6 left)
        (next loc_27_6 loc_27_5 down)
        (patterned loc_25_2 red)
        (patterned loc_26_2 orange)
        (patterned loc_27_2 yellow)
        (patterned loc_2_6 red)
        (patterned loc_3_6 orange)
        (patterned loc_4_6 yellow)
    )

    (:goal
        (forall (?l - location)
            (not (exists (?p - pattern)
                (patterned ?l ?p)))))

    (:metric minimize (total-cost))
)
