; generated by prob2pddl.py problem-5x24-test.prob
; #####
; #R R#
; #P B#
; ## ##
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #B P#
; #####
; R:2 B:2 P:2 blocks:6 spaces:58
(define (problem problem-5x24-test)
(:domain puzznic)

    (:objects
        red - pattern
        orange - pattern
        yellow - pattern
        green - pattern
        blue - pattern
        violet - pattern
        pink - pattern
        coal - pattern
        lightblue - pattern
        loc_1_1 - location
        loc_2_1 - location
        loc_3_1 - location
        loc_4_1 - location
        loc_5_1 - location
        loc_1_2 - location
        loc_2_2 - location
        loc_3_2 - location
        loc_4_2 - location
        loc_5_2 - location
        loc_1_3 - location
        loc_2_3 - location
        loc_3_3 - location
        loc_4_3 - location
        loc_5_3 - location
        loc_1_4 - location
        loc_2_4 - location
        loc_3_4 - location
        loc_4_4 - location
        loc_5_4 - location
        loc_1_5 - location
        loc_2_5 - location
        loc_3_5 - location
        loc_4_5 - location
        loc_5_5 - location
        loc_1_6 - location
        loc_2_6 - location
        loc_3_6 - location
        loc_4_6 - location
        loc_5_6 - location
        loc_1_7 - location
        loc_2_7 - location
        loc_3_7 - location
        loc_4_7 - location
        loc_5_7 - location
        loc_1_8 - location
        loc_2_8 - location
        loc_3_8 - location
        loc_4_8 - location
        loc_5_8 - location
        loc_1_9 - location
        loc_2_9 - location
        loc_3_9 - location
        loc_4_9 - location
        loc_5_9 - location
        loc_1_10 - location
        loc_2_10 - location
        loc_3_10 - location
        loc_4_10 - location
        loc_5_10 - location
        loc_1_11 - location
        loc_2_11 - location
        loc_3_11 - location
        loc_4_11 - location
        loc_5_11 - location
        loc_1_12 - location
        loc_2_12 - location
        loc_3_12 - location
        loc_4_12 - location
        loc_5_12 - location
        loc_1_13 - location
        loc_2_13 - location
        loc_3_13 - location
        loc_4_13 - location
        loc_5_13 - location
        loc_1_14 - location
        loc_2_14 - location
        loc_3_14 - location
        loc_4_14 - location
        loc_5_14 - location
        loc_1_15 - location
        loc_2_15 - location
        loc_3_15 - location
        loc_4_15 - location
        loc_5_15 - location
        loc_1_16 - location
        loc_2_16 - location
        loc_3_16 - location
        loc_4_16 - location
        loc_5_16 - location
        loc_1_17 - location
        loc_2_17 - location
        loc_3_17 - location
        loc_4_17 - location
        loc_5_17 - location
        loc_1_18 - location
        loc_2_18 - location
        loc_3_18 - location
        loc_4_18 - location
        loc_5_18 - location
        loc_1_19 - location
        loc_2_19 - location
        loc_3_19 - location
        loc_4_19 - location
        loc_5_19 - location
        loc_1_20 - location
        loc_2_20 - location
        loc_3_20 - location
        loc_4_20 - location
        loc_5_20 - location
        loc_1_21 - location
        loc_2_21 - location
        loc_3_21 - location
        loc_4_21 - location
        loc_5_21 - location
        loc_1_22 - location
        loc_2_22 - location
        loc_3_22 - location
        loc_4_22 - location
        loc_5_22 - location
        loc_1_23 - location
        loc_2_23 - location
        loc_3_23 - location
        loc_4_23 - location
        loc_5_23 - location
        loc_1_24 - location
        loc_2_24 - location
        loc_3_24 - location
        loc_4_24 - location
        loc_5_24 - location
)
    (:init
        (= (total-cost) 0)
        (next loc_2_2 loc_3_2 right)
        (next loc_2_2 loc_2_3 up)
        (next loc_3_2 loc_2_2 left)
        (next loc_3_2 loc_4_2 right)
        (next loc_3_2 loc_3_3 up)
        (next loc_4_2 loc_3_2 left)
        (next loc_4_2 loc_4_3 up)
        (next loc_2_3 loc_3_3 right)
        (next loc_2_3 loc_2_4 up)
        (next loc_2_3 loc_2_2 down)
        (next loc_3_3 loc_2_3 left)
        (next loc_3_3 loc_4_3 right)
        (next loc_3_3 loc_3_4 up)
        (next loc_3_3 loc_3_2 down)
        (next loc_4_3 loc_3_3 left)
        (next loc_4_3 loc_4_4 up)
        (next loc_4_3 loc_4_2 down)
        (next loc_2_4 loc_3_4 right)
        (next loc_2_4 loc_2_5 up)
        (next loc_2_4 loc_2_3 down)
        (next loc_3_4 loc_2_4 left)
        (next loc_3_4 loc_4_4 right)
        (next loc_3_4 loc_3_5 up)
        (next loc_3_4 loc_3_3 down)
        (next loc_4_4 loc_3_4 left)
        (next loc_4_4 loc_4_5 up)
        (next loc_4_4 loc_4_3 down)
        (next loc_2_5 loc_3_5 right)
        (next loc_2_5 loc_2_6 up)
        (next loc_2_5 loc_2_4 down)
        (next loc_3_5 loc_2_5 left)
        (next loc_3_5 loc_4_5 right)
        (next loc_3_5 loc_3_6 up)
        (next loc_3_5 loc_3_4 down)
        (next loc_4_5 loc_3_5 left)
        (next loc_4_5 loc_4_6 up)
        (next loc_4_5 loc_4_4 down)
        (next loc_2_6 loc_3_6 right)
        (next loc_2_6 loc_2_7 up)
        (next loc_2_6 loc_2_5 down)
        (next loc_3_6 loc_2_6 left)
        (next loc_3_6 loc_4_6 right)
        (next loc_3_6 loc_3_7 up)
        (next loc_3_6 loc_3_5 down)
        (next loc_4_6 loc_3_6 left)
        (next loc_4_6 loc_4_7 up)
        (next loc_4_6 loc_4_5 down)
        (next loc_2_7 loc_3_7 right)
        (next loc_2_7 loc_2_8 up)
        (next loc_2_7 loc_2_6 down)
        (next loc_3_7 loc_2_7 left)
        (next loc_3_7 loc_4_7 right)
        (next loc_3_7 loc_3_8 up)
        (next loc_3_7 loc_3_6 down)
        (next loc_4_7 loc_3_7 left)
        (next loc_4_7 loc_4_8 up)
        (next loc_4_7 loc_4_6 down)
        (next loc_2_8 loc_3_8 right)
        (next loc_2_8 loc_2_9 up)
        (next loc_2_8 loc_2_7 down)
        (next loc_3_8 loc_2_8 left)
        (next loc_3_8 loc_4_8 right)
        (next loc_3_8 loc_3_9 up)
        (next loc_3_8 loc_3_7 down)
        (next loc_4_8 loc_3_8 left)
        (next loc_4_8 loc_4_9 up)
        (next loc_4_8 loc_4_7 down)
        (next loc_2_9 loc_3_9 right)
        (next loc_2_9 loc_2_10 up)
        (next loc_2_9 loc_2_8 down)
        (next loc_3_9 loc_2_9 left)
        (next loc_3_9 loc_4_9 right)
        (next loc_3_9 loc_3_10 up)
        (next loc_3_9 loc_3_8 down)
        (next loc_4_9 loc_3_9 left)
        (next loc_4_9 loc_4_10 up)
        (next loc_4_9 loc_4_8 down)
        (next loc_2_10 loc_3_10 right)
        (next loc_2_10 loc_2_11 up)
        (next loc_2_10 loc_2_9 down)
        (next loc_3_10 loc_2_10 left)
        (next loc_3_10 loc_4_10 right)
        (next loc_3_10 loc_3_11 up)
        (next loc_3_10 loc_3_9 down)
        (next loc_4_10 loc_3_10 left)
        (next loc_4_10 loc_4_11 up)
        (next loc_4_10 loc_4_9 down)
        (next loc_2_11 loc_3_11 right)
        (next loc_2_11 loc_2_12 up)
        (next loc_2_11 loc_2_10 down)
        (next loc_3_11 loc_2_11 left)
        (next loc_3_11 loc_4_11 right)
        (next loc_3_11 loc_3_12 up)
        (next loc_3_11 loc_3_10 down)
        (next loc_4_11 loc_3_11 left)
        (next loc_4_11 loc_4_12 up)
        (next loc_4_11 loc_4_10 down)
        (next loc_2_12 loc_3_12 right)
        (next loc_2_12 loc_2_13 up)
        (next loc_2_12 loc_2_11 down)
        (next loc_3_12 loc_2_12 left)
        (next loc_3_12 loc_4_12 right)
        (next loc_3_12 loc_3_13 up)
        (next loc_3_12 loc_3_11 down)
        (next loc_4_12 loc_3_12 left)
        (next loc_4_12 loc_4_13 up)
        (next loc_4_12 loc_4_11 down)
        (next loc_2_13 loc_3_13 right)
        (next loc_2_13 loc_2_14 up)
        (next loc_2_13 loc_2_12 down)
        (next loc_3_13 loc_2_13 left)
        (next loc_3_13 loc_4_13 right)
        (next loc_3_13 loc_3_14 up)
        (next loc_3_13 loc_3_12 down)
        (next loc_4_13 loc_3_13 left)
        (next loc_4_13 loc_4_14 up)
        (next loc_4_13 loc_4_12 down)
        (next loc_2_14 loc_3_14 right)
        (next loc_2_14 loc_2_15 up)
        (next loc_2_14 loc_2_13 down)
        (next loc_3_14 loc_2_14 left)
        (next loc_3_14 loc_4_14 right)
        (next loc_3_14 loc_3_15 up)
        (next loc_3_14 loc_3_13 down)
        (next loc_4_14 loc_3_14 left)
        (next loc_4_14 loc_4_15 up)
        (next loc_4_14 loc_4_13 down)
        (next loc_2_15 loc_3_15 right)
        (next loc_2_15 loc_2_16 up)
        (next loc_2_15 loc_2_14 down)
        (next loc_3_15 loc_2_15 left)
        (next loc_3_15 loc_4_15 right)
        (next loc_3_15 loc_3_16 up)
        (next loc_3_15 loc_3_14 down)
        (next loc_4_15 loc_3_15 left)
        (next loc_4_15 loc_4_16 up)
        (next loc_4_15 loc_4_14 down)
        (next loc_2_16 loc_3_16 right)
        (next loc_2_16 loc_2_17 up)
        (next loc_2_16 loc_2_15 down)
        (next loc_3_16 loc_2_16 left)
        (next loc_3_16 loc_4_16 right)
        (next loc_3_16 loc_3_17 up)
        (next loc_3_16 loc_3_15 down)
        (next loc_4_16 loc_3_16 left)
        (next loc_4_16 loc_4_17 up)
        (next loc_4_16 loc_4_15 down)
        (next loc_2_17 loc_3_17 right)
        (next loc_2_17 loc_2_18 up)
        (next loc_2_17 loc_2_16 down)
        (next loc_3_17 loc_2_17 left)
        (next loc_3_17 loc_4_17 right)
        (next loc_3_17 loc_3_18 up)
        (next loc_3_17 loc_3_16 down)
        (next loc_4_17 loc_3_17 left)
        (next loc_4_17 loc_4_18 up)
        (next loc_4_17 loc_4_16 down)
        (next loc_2_18 loc_3_18 right)
        (next loc_2_18 loc_2_19 up)
        (next loc_2_18 loc_2_17 down)
        (next loc_3_18 loc_2_18 left)
        (next loc_3_18 loc_4_18 right)
        (next loc_3_18 loc_3_19 up)
        (next loc_3_18 loc_3_17 down)
        (next loc_4_18 loc_3_18 left)
        (next loc_4_18 loc_4_19 up)
        (next loc_4_18 loc_4_17 down)
        (next loc_2_19 loc_3_19 right)
        (next loc_2_19 loc_2_20 up)
        (next loc_2_19 loc_2_18 down)
        (next loc_3_19 loc_2_19 left)
        (next loc_3_19 loc_4_19 right)
        (next loc_3_19 loc_3_20 up)
        (next loc_3_19 loc_3_18 down)
        (next loc_4_19 loc_3_19 left)
        (next loc_4_19 loc_4_20 up)
        (next loc_4_19 loc_4_18 down)
        (next loc_2_20 loc_3_20 right)
        (next loc_2_20 loc_2_19 down)
        (next loc_3_20 loc_2_20 left)
        (next loc_3_20 loc_4_20 right)
        (next loc_3_20 loc_3_21 up)
        (next loc_3_20 loc_3_19 down)
        (next loc_4_20 loc_3_20 left)
        (next loc_4_20 loc_4_19 down)
        (next loc_3_21 loc_3_22 up)
        (next loc_3_21 loc_3_20 down)
        (next loc_2_22 loc_3_22 right)
        (next loc_2_22 loc_2_23 up)
        (next loc_3_22 loc_2_22 left)
        (next loc_3_22 loc_4_22 right)
        (next loc_3_22 loc_3_23 up)
        (next loc_3_22 loc_3_21 down)
        (next loc_4_22 loc_3_22 left)
        (next loc_4_22 loc_4_23 up)
        (next loc_2_23 loc_3_23 right)
        (next loc_2_23 loc_2_22 down)
        (next loc_3_23 loc_2_23 left)
        (next loc_3_23 loc_4_23 right)
        (next loc_3_23 loc_3_22 down)
        (next loc_4_23 loc_3_23 left)
        (next loc_4_23 loc_4_22 down)
        (patterned loc_2_2 blue)
        (patterned loc_4_2 pink)
        (patterned loc_2_22 pink)
        (patterned loc_4_22 blue)
        (patterned loc_2_23 red)
        (patterned loc_4_23 red)
    )

    (:goal
        (forall (?l - location)
            (not (exists (?p - pattern)
                (patterned ?l ?p)))))

    (:metric minimize (total-cost))
)
