; generated by prob2pddl.py problem-5x50-test.prob
; #####
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #   #
; #R R#
; #P B#
; ## ##
; #   #
; #B P#
; #####
; R:2 B:2 P:2 blocks:6 spaces:136
(define (problem problem-5x50-test)
(:domain puzznic)

    (:objects
        red - pattern
        orange - pattern
        yellow - pattern
        green - pattern
        blue - pattern
        violet - pattern
        pink - pattern
        coal - pattern
        lightblue - pattern
        loc_1_1 - location
        loc_2_1 - location
        loc_3_1 - location
        loc_4_1 - location
        loc_5_1 - location
        loc_1_2 - location
        loc_2_2 - location
        loc_3_2 - location
        loc_4_2 - location
        loc_5_2 - location
        loc_1_3 - location
        loc_2_3 - location
        loc_3_3 - location
        loc_4_3 - location
        loc_5_3 - location
        loc_1_4 - location
        loc_2_4 - location
        loc_3_4 - location
        loc_4_4 - location
        loc_5_4 - location
        loc_1_5 - location
        loc_2_5 - location
        loc_3_5 - location
        loc_4_5 - location
        loc_5_5 - location
        loc_1_6 - location
        loc_2_6 - location
        loc_3_6 - location
        loc_4_6 - location
        loc_5_6 - location
        loc_1_7 - location
        loc_2_7 - location
        loc_3_7 - location
        loc_4_7 - location
        loc_5_7 - location
        loc_1_8 - location
        loc_2_8 - location
        loc_3_8 - location
        loc_4_8 - location
        loc_5_8 - location
        loc_1_9 - location
        loc_2_9 - location
        loc_3_9 - location
        loc_4_9 - location
        loc_5_9 - location
        loc_1_10 - location
        loc_2_10 - location
        loc_3_10 - location
        loc_4_10 - location
        loc_5_10 - location
        loc_1_11 - location
        loc_2_11 - location
        loc_3_11 - location
        loc_4_11 - location
        loc_5_11 - location
        loc_1_12 - location
        loc_2_12 - location
        loc_3_12 - location
        loc_4_12 - location
        loc_5_12 - location
        loc_1_13 - location
        loc_2_13 - location
        loc_3_13 - location
        loc_4_13 - location
        loc_5_13 - location
        loc_1_14 - location
        loc_2_14 - location
        loc_3_14 - location
        loc_4_14 - location
        loc_5_14 - location
        loc_1_15 - location
        loc_2_15 - location
        loc_3_15 - location
        loc_4_15 - location
        loc_5_15 - location
        loc_1_16 - location
        loc_2_16 - location
        loc_3_16 - location
        loc_4_16 - location
        loc_5_16 - location
        loc_1_17 - location
        loc_2_17 - location
        loc_3_17 - location
        loc_4_17 - location
        loc_5_17 - location
        loc_1_18 - location
        loc_2_18 - location
        loc_3_18 - location
        loc_4_18 - location
        loc_5_18 - location
        loc_1_19 - location
        loc_2_19 - location
        loc_3_19 - location
        loc_4_19 - location
        loc_5_19 - location
        loc_1_20 - location
        loc_2_20 - location
        loc_3_20 - location
        loc_4_20 - location
        loc_5_20 - location
        loc_1_21 - location
        loc_2_21 - location
        loc_3_21 - location
        loc_4_21 - location
        loc_5_21 - location
        loc_1_22 - location
        loc_2_22 - location
        loc_3_22 - location
        loc_4_22 - location
        loc_5_22 - location
        loc_1_23 - location
        loc_2_23 - location
        loc_3_23 - location
        loc_4_23 - location
        loc_5_23 - location
        loc_1_24 - location
        loc_2_24 - location
        loc_3_24 - location
        loc_4_24 - location
        loc_5_24 - location
        loc_1_25 - location
        loc_2_25 - location
        loc_3_25 - location
        loc_4_25 - location
        loc_5_25 - location
        loc_1_26 - location
        loc_2_26 - location
        loc_3_26 - location
        loc_4_26 - location
        loc_5_26 - location
        loc_1_27 - location
        loc_2_27 - location
        loc_3_27 - location
        loc_4_27 - location
        loc_5_27 - location
        loc_1_28 - location
        loc_2_28 - location
        loc_3_28 - location
        loc_4_28 - location
        loc_5_28 - location
        loc_1_29 - location
        loc_2_29 - location
        loc_3_29 - location
        loc_4_29 - location
        loc_5_29 - location
        loc_1_30 - location
        loc_2_30 - location
        loc_3_30 - location
        loc_4_30 - location
        loc_5_30 - location
        loc_1_31 - location
        loc_2_31 - location
        loc_3_31 - location
        loc_4_31 - location
        loc_5_31 - location
        loc_1_32 - location
        loc_2_32 - location
        loc_3_32 - location
        loc_4_32 - location
        loc_5_32 - location
        loc_1_33 - location
        loc_2_33 - location
        loc_3_33 - location
        loc_4_33 - location
        loc_5_33 - location
        loc_1_34 - location
        loc_2_34 - location
        loc_3_34 - location
        loc_4_34 - location
        loc_5_34 - location
        loc_1_35 - location
        loc_2_35 - location
        loc_3_35 - location
        loc_4_35 - location
        loc_5_35 - location
        loc_1_36 - location
        loc_2_36 - location
        loc_3_36 - location
        loc_4_36 - location
        loc_5_36 - location
        loc_1_37 - location
        loc_2_37 - location
        loc_3_37 - location
        loc_4_37 - location
        loc_5_37 - location
        loc_1_38 - location
        loc_2_38 - location
        loc_3_38 - location
        loc_4_38 - location
        loc_5_38 - location
        loc_1_39 - location
        loc_2_39 - location
        loc_3_39 - location
        loc_4_39 - location
        loc_5_39 - location
        loc_1_40 - location
        loc_2_40 - location
        loc_3_40 - location
        loc_4_40 - location
        loc_5_40 - location
        loc_1_41 - location
        loc_2_41 - location
        loc_3_41 - location
        loc_4_41 - location
        loc_5_41 - location
        loc_1_42 - location
        loc_2_42 - location
        loc_3_42 - location
        loc_4_42 - location
        loc_5_42 - location
        loc_1_43 - location
        loc_2_43 - location
        loc_3_43 - location
        loc_4_43 - location
        loc_5_43 - location
        loc_1_44 - location
        loc_2_44 - location
        loc_3_44 - location
        loc_4_44 - location
        loc_5_44 - location
        loc_1_45 - location
        loc_2_45 - location
        loc_3_45 - location
        loc_4_45 - location
        loc_5_45 - location
        loc_1_46 - location
        loc_2_46 - location
        loc_3_46 - location
        loc_4_46 - location
        loc_5_46 - location
        loc_1_47 - location
        loc_2_47 - location
        loc_3_47 - location
        loc_4_47 - location
        loc_5_47 - location
        loc_1_48 - location
        loc_2_48 - location
        loc_3_48 - location
        loc_4_48 - location
        loc_5_48 - location
        loc_1_49 - location
        loc_2_49 - location
        loc_3_49 - location
        loc_4_49 - location
        loc_5_49 - location
        loc_1_50 - location
        loc_2_50 - location
        loc_3_50 - location
        loc_4_50 - location
        loc_5_50 - location
)
    (:init
        (= (total-cost) 0)
        (next loc_2_2 loc_3_2 right)
        (next loc_2_2 loc_2_3 up)
        (next loc_3_2 loc_2_2 left)
        (next loc_3_2 loc_4_2 right)
        (next loc_3_2 loc_3_3 up)
        (next loc_4_2 loc_3_2 left)
        (next loc_4_2 loc_4_3 up)
        (next loc_2_3 loc_3_3 right)
        (next loc_2_3 loc_2_2 down)
        (next loc_3_3 loc_2_3 left)
        (next loc_3_3 loc_4_3 right)
        (next loc_3_3 loc_3_4 up)
        (next loc_3_3 loc_3_2 down)
        (next loc_4_3 loc_3_3 left)
        (next loc_4_3 loc_4_2 down)
        (next loc_3_4 loc_3_5 up)
        (next loc_3_4 loc_3_3 down)
        (next loc_2_5 loc_3_5 right)
        (next loc_2_5 loc_2_6 up)
        (next loc_3_5 loc_2_5 left)
        (next loc_3_5 loc_4_5 right)
        (next loc_3_5 loc_3_6 up)
        (next loc_3_5 loc_3_4 down)
        (next loc_4_5 loc_3_5 left)
        (next loc_4_5 loc_4_6 up)
        (next loc_2_6 loc_3_6 right)
        (next loc_2_6 loc_2_7 up)
        (next loc_2_6 loc_2_5 down)
        (next loc_3_6 loc_2_6 left)
        (next loc_3_6 loc_4_6 right)
        (next loc_3_6 loc_3_7 up)
        (next loc_3_6 loc_3_5 down)
        (next loc_4_6 loc_3_6 left)
        (next loc_4_6 loc_4_7 up)
        (next loc_4_6 loc_4_5 down)
        (next loc_2_7 loc_3_7 right)
        (next loc_2_7 loc_2_8 up)
        (next loc_2_7 loc_2_6 down)
        (next loc_3_7 loc_2_7 left)
        (next loc_3_7 loc_4_7 right)
        (next loc_3_7 loc_3_8 up)
        (next loc_3_7 loc_3_6 down)
        (next loc_4_7 loc_3_7 left)
        (next loc_4_7 loc_4_8 up)
        (next loc_4_7 loc_4_6 down)
        (next loc_2_8 loc_3_8 right)
        (next loc_2_8 loc_2_9 up)
        (next loc_2_8 loc_2_7 down)
        (next loc_3_8 loc_2_8 left)
        (next loc_3_8 loc_4_8 right)
        (next loc_3_8 loc_3_9 up)
        (next loc_3_8 loc_3_7 down)
        (next loc_4_8 loc_3_8 left)
        (next loc_4_8 loc_4_9 up)
        (next loc_4_8 loc_4_7 down)
        (next loc_2_9 loc_3_9 right)
        (next loc_2_9 loc_2_10 up)
        (next loc_2_9 loc_2_8 down)
        (next loc_3_9 loc_2_9 left)
        (next loc_3_9 loc_4_9 right)
        (next loc_3_9 loc_3_10 up)
        (next loc_3_9 loc_3_8 down)
        (next loc_4_9 loc_3_9 left)
        (next loc_4_9 loc_4_10 up)
        (next loc_4_9 loc_4_8 down)
        (next loc_2_10 loc_3_10 right)
        (next loc_2_10 loc_2_11 up)
        (next loc_2_10 loc_2_9 down)
        (next loc_3_10 loc_2_10 left)
        (next loc_3_10 loc_4_10 right)
        (next loc_3_10 loc_3_11 up)
        (next loc_3_10 loc_3_9 down)
        (next loc_4_10 loc_3_10 left)
        (next loc_4_10 loc_4_11 up)
        (next loc_4_10 loc_4_9 down)
        (next loc_2_11 loc_3_11 right)
        (next loc_2_11 loc_2_12 up)
        (next loc_2_11 loc_2_10 down)
        (next loc_3_11 loc_2_11 left)
        (next loc_3_11 loc_4_11 right)
        (next loc_3_11 loc_3_12 up)
        (next loc_3_11 loc_3_10 down)
        (next loc_4_11 loc_3_11 left)
        (next loc_4_11 loc_4_12 up)
        (next loc_4_11 loc_4_10 down)
        (next loc_2_12 loc_3_12 right)
        (next loc_2_12 loc_2_13 up)
        (next loc_2_12 loc_2_11 down)
        (next loc_3_12 loc_2_12 left)
        (next loc_3_12 loc_4_12 right)
        (next loc_3_12 loc_3_13 up)
        (next loc_3_12 loc_3_11 down)
        (next loc_4_12 loc_3_12 left)
        (next loc_4_12 loc_4_13 up)
        (next loc_4_12 loc_4_11 down)
        (next loc_2_13 loc_3_13 right)
        (next loc_2_13 loc_2_14 up)
        (next loc_2_13 loc_2_12 down)
        (next loc_3_13 loc_2_13 left)
        (next loc_3_13 loc_4_13 right)
        (next loc_3_13 loc_3_14 up)
        (next loc_3_13 loc_3_12 down)
        (next loc_4_13 loc_3_13 left)
        (next loc_4_13 loc_4_14 up)
        (next loc_4_13 loc_4_12 down)
        (next loc_2_14 loc_3_14 right)
        (next loc_2_14 loc_2_15 up)
        (next loc_2_14 loc_2_13 down)
        (next loc_3_14 loc_2_14 left)
        (next loc_3_14 loc_4_14 right)
        (next loc_3_14 loc_3_15 up)
        (next loc_3_14 loc_3_13 down)
        (next loc_4_14 loc_3_14 left)
        (next loc_4_14 loc_4_15 up)
        (next loc_4_14 loc_4_13 down)
        (next loc_2_15 loc_3_15 right)
        (next loc_2_15 loc_2_16 up)
        (next loc_2_15 loc_2_14 down)
        (next loc_3_15 loc_2_15 left)
        (next loc_3_15 loc_4_15 right)
        (next loc_3_15 loc_3_16 up)
        (next loc_3_15 loc_3_14 down)
        (next loc_4_15 loc_3_15 left)
        (next loc_4_15 loc_4_16 up)
        (next loc_4_15 loc_4_14 down)
        (next loc_2_16 loc_3_16 right)
        (next loc_2_16 loc_2_17 up)
        (next loc_2_16 loc_2_15 down)
        (next loc_3_16 loc_2_16 left)
        (next loc_3_16 loc_4_16 right)
        (next loc_3_16 loc_3_17 up)
        (next loc_3_16 loc_3_15 down)
        (next loc_4_16 loc_3_16 left)
        (next loc_4_16 loc_4_17 up)
        (next loc_4_16 loc_4_15 down)
        (next loc_2_17 loc_3_17 right)
        (next loc_2_17 loc_2_18 up)
        (next loc_2_17 loc_2_16 down)
        (next loc_3_17 loc_2_17 left)
        (next loc_3_17 loc_4_17 right)
        (next loc_3_17 loc_3_18 up)
        (next loc_3_17 loc_3_16 down)
        (next loc_4_17 loc_3_17 left)
        (next loc_4_17 loc_4_18 up)
        (next loc_4_17 loc_4_16 down)
        (next loc_2_18 loc_3_18 right)
        (next loc_2_18 loc_2_19 up)
        (next loc_2_18 loc_2_17 down)
        (next loc_3_18 loc_2_18 left)
        (next loc_3_18 loc_4_18 right)
        (next loc_3_18 loc_3_19 up)
        (next loc_3_18 loc_3_17 down)
        (next loc_4_18 loc_3_18 left)
        (next loc_4_18 loc_4_19 up)
        (next loc_4_18 loc_4_17 down)
        (next loc_2_19 loc_3_19 right)
        (next loc_2_19 loc_2_20 up)
        (next loc_2_19 loc_2_18 down)
        (next loc_3_19 loc_2_19 left)
        (next loc_3_19 loc_4_19 right)
        (next loc_3_19 loc_3_20 up)
        (next loc_3_19 loc_3_18 down)
        (next loc_4_19 loc_3_19 left)
        (next loc_4_19 loc_4_20 up)
        (next loc_4_19 loc_4_18 down)
        (next loc_2_20 loc_3_20 right)
        (next loc_2_20 loc_2_21 up)
        (next loc_2_20 loc_2_19 down)
        (next loc_3_20 loc_2_20 left)
        (next loc_3_20 loc_4_20 right)
        (next loc_3_20 loc_3_21 up)
        (next loc_3_20 loc_3_19 down)
        (next loc_4_20 loc_3_20 left)
        (next loc_4_20 loc_4_21 up)
        (next loc_4_20 loc_4_19 down)
        (next loc_2_21 loc_3_21 right)
        (next loc_2_21 loc_2_22 up)
        (next loc_2_21 loc_2_20 down)
        (next loc_3_21 loc_2_21 left)
        (next loc_3_21 loc_4_21 right)
        (next loc_3_21 loc_3_22 up)
        (next loc_3_21 loc_3_20 down)
        (next loc_4_21 loc_3_21 left)
        (next loc_4_21 loc_4_22 up)
        (next loc_4_21 loc_4_20 down)
        (next loc_2_22 loc_3_22 right)
        (next loc_2_22 loc_2_23 up)
        (next loc_2_22 loc_2_21 down)
        (next loc_3_22 loc_2_22 left)
        (next loc_3_22 loc_4_22 right)
        (next loc_3_22 loc_3_23 up)
        (next loc_3_22 loc_3_21 down)
        (next loc_4_22 loc_3_22 left)
        (next loc_4_22 loc_4_23 up)
        (next loc_4_22 loc_4_21 down)
        (next loc_2_23 loc_3_23 right)
        (next loc_2_23 loc_2_24 up)
        (next loc_2_23 loc_2_22 down)
        (next loc_3_23 loc_2_23 left)
        (next loc_3_23 loc_4_23 right)
        (next loc_3_23 loc_3_24 up)
        (next loc_3_23 loc_3_22 down)
        (next loc_4_23 loc_3_23 left)
        (next loc_4_23 loc_4_24 up)
        (next loc_4_23 loc_4_22 down)
        (next loc_2_24 loc_3_24 right)
        (next loc_2_24 loc_2_25 up)
        (next loc_2_24 loc_2_23 down)
        (next loc_3_24 loc_2_24 left)
        (next loc_3_24 loc_4_24 right)
        (next loc_3_24 loc_3_25 up)
        (next loc_3_24 loc_3_23 down)
        (next loc_4_24 loc_3_24 left)
        (next loc_4_24 loc_4_25 up)
        (next loc_4_24 loc_4_23 down)
        (next loc_2_25 loc_3_25 right)
        (next loc_2_25 loc_2_26 up)
        (next loc_2_25 loc_2_24 down)
        (next loc_3_25 loc_2_25 left)
        (next loc_3_25 loc_4_25 right)
        (next loc_3_25 loc_3_26 up)
        (next loc_3_25 loc_3_24 down)
        (next loc_4_25 loc_3_25 left)
        (next loc_4_25 loc_4_26 up)
        (next loc_4_25 loc_4_24 down)
        (next loc_2_26 loc_3_26 right)
        (next loc_2_26 loc_2_27 up)
        (next loc_2_26 loc_2_25 down)
        (next loc_3_26 loc_2_26 left)
        (next loc_3_26 loc_4_26 right)
        (next loc_3_26 loc_3_27 up)
        (next loc_3_26 loc_3_25 down)
        (next loc_4_26 loc_3_26 left)
        (next loc_4_26 loc_4_27 up)
        (next loc_4_26 loc_4_25 down)
        (next loc_2_27 loc_3_27 right)
        (next loc_2_27 loc_2_28 up)
        (next loc_2_27 loc_2_26 down)
        (next loc_3_27 loc_2_27 left)
        (next loc_3_27 loc_4_27 right)
        (next loc_3_27 loc_3_28 up)
        (next loc_3_27 loc_3_26 down)
        (next loc_4_27 loc_3_27 left)
        (next loc_4_27 loc_4_28 up)
        (next loc_4_27 loc_4_26 down)
        (next loc_2_28 loc_3_28 right)
        (next loc_2_28 loc_2_29 up)
        (next loc_2_28 loc_2_27 down)
        (next loc_3_28 loc_2_28 left)
        (next loc_3_28 loc_4_28 right)
        (next loc_3_28 loc_3_29 up)
        (next loc_3_28 loc_3_27 down)
        (next loc_4_28 loc_3_28 left)
        (next loc_4_28 loc_4_29 up)
        (next loc_4_28 loc_4_27 down)
        (next loc_2_29 loc_3_29 right)
        (next loc_2_29 loc_2_30 up)
        (next loc_2_29 loc_2_28 down)
        (next loc_3_29 loc_2_29 left)
        (next loc_3_29 loc_4_29 right)
        (next loc_3_29 loc_3_30 up)
        (next loc_3_29 loc_3_28 down)
        (next loc_4_29 loc_3_29 left)
        (next loc_4_29 loc_4_30 up)
        (next loc_4_29 loc_4_28 down)
        (next loc_2_30 loc_3_30 right)
        (next loc_2_30 loc_2_31 up)
        (next loc_2_30 loc_2_29 down)
        (next loc_3_30 loc_2_30 left)
        (next loc_3_30 loc_4_30 right)
        (next loc_3_30 loc_3_31 up)
        (next loc_3_30 loc_3_29 down)
        (next loc_4_30 loc_3_30 left)
        (next loc_4_30 loc_4_31 up)
        (next loc_4_30 loc_4_29 down)
        (next loc_2_31 loc_3_31 right)
        (next loc_2_31 loc_2_32 up)
        (next loc_2_31 loc_2_30 down)
        (next loc_3_31 loc_2_31 left)
        (next loc_3_31 loc_4_31 right)
        (next loc_3_31 loc_3_32 up)
        (next loc_3_31 loc_3_30 down)
        (next loc_4_31 loc_3_31 left)
        (next loc_4_31 loc_4_32 up)
        (next loc_4_31 loc_4_30 down)
        (next loc_2_32 loc_3_32 right)
        (next loc_2_32 loc_2_33 up)
        (next loc_2_32 loc_2_31 down)
        (next loc_3_32 loc_2_32 left)
        (next loc_3_32 loc_4_32 right)
        (next loc_3_32 loc_3_33 up)
        (next loc_3_32 loc_3_31 down)
        (next loc_4_32 loc_3_32 left)
        (next loc_4_32 loc_4_33 up)
        (next loc_4_32 loc_4_31 down)
        (next loc_2_33 loc_3_33 right)
        (next loc_2_33 loc_2_34 up)
        (next loc_2_33 loc_2_32 down)
        (next loc_3_33 loc_2_33 left)
        (next loc_3_33 loc_4_33 right)
        (next loc_3_33 loc_3_34 up)
        (next loc_3_33 loc_3_32 down)
        (next loc_4_33 loc_3_33 left)
        (next loc_4_33 loc_4_34 up)
        (next loc_4_33 loc_4_32 down)
        (next loc_2_34 loc_3_34 right)
        (next loc_2_34 loc_2_35 up)
        (next loc_2_34 loc_2_33 down)
        (next loc_3_34 loc_2_34 left)
        (next loc_3_34 loc_4_34 right)
        (next loc_3_34 loc_3_35 up)
        (next loc_3_34 loc_3_33 down)
        (next loc_4_34 loc_3_34 left)
        (next loc_4_34 loc_4_35 up)
        (next loc_4_34 loc_4_33 down)
        (next loc_2_35 loc_3_35 right)
        (next loc_2_35 loc_2_36 up)
        (next loc_2_35 loc_2_34 down)
        (next loc_3_35 loc_2_35 left)
        (next loc_3_35 loc_4_35 right)
        (next loc_3_35 loc_3_36 up)
        (next loc_3_35 loc_3_34 down)
        (next loc_4_35 loc_3_35 left)
        (next loc_4_35 loc_4_36 up)
        (next loc_4_35 loc_4_34 down)
        (next loc_2_36 loc_3_36 right)
        (next loc_2_36 loc_2_37 up)
        (next loc_2_36 loc_2_35 down)
        (next loc_3_36 loc_2_36 left)
        (next loc_3_36 loc_4_36 right)
        (next loc_3_36 loc_3_37 up)
        (next loc_3_36 loc_3_35 down)
        (next loc_4_36 loc_3_36 left)
        (next loc_4_36 loc_4_37 up)
        (next loc_4_36 loc_4_35 down)
        (next loc_2_37 loc_3_37 right)
        (next loc_2_37 loc_2_38 up)
        (next loc_2_37 loc_2_36 down)
        (next loc_3_37 loc_2_37 left)
        (next loc_3_37 loc_4_37 right)
        (next loc_3_37 loc_3_38 up)
        (next loc_3_37 loc_3_36 down)
        (next loc_4_37 loc_3_37 left)
        (next loc_4_37 loc_4_38 up)
        (next loc_4_37 loc_4_36 down)
        (next loc_2_38 loc_3_38 right)
        (next loc_2_38 loc_2_39 up)
        (next loc_2_38 loc_2_37 down)
        (next loc_3_38 loc_2_38 left)
        (next loc_3_38 loc_4_38 right)
        (next loc_3_38 loc_3_39 up)
        (next loc_3_38 loc_3_37 down)
        (next loc_4_38 loc_3_38 left)
        (next loc_4_38 loc_4_39 up)
        (next loc_4_38 loc_4_37 down)
        (next loc_2_39 loc_3_39 right)
        (next loc_2_39 loc_2_40 up)
        (next loc_2_39 loc_2_38 down)
        (next loc_3_39 loc_2_39 left)
        (next loc_3_39 loc_4_39 right)
        (next loc_3_39 loc_3_40 up)
        (next loc_3_39 loc_3_38 down)
        (next loc_4_39 loc_3_39 left)
        (next loc_4_39 loc_4_40 up)
        (next loc_4_39 loc_4_38 down)
        (next loc_2_40 loc_3_40 right)
        (next loc_2_40 loc_2_41 up)
        (next loc_2_40 loc_2_39 down)
        (next loc_3_40 loc_2_40 left)
        (next loc_3_40 loc_4_40 right)
        (next loc_3_40 loc_3_41 up)
        (next loc_3_40 loc_3_39 down)
        (next loc_4_40 loc_3_40 left)
        (next loc_4_40 loc_4_41 up)
        (next loc_4_40 loc_4_39 down)
        (next loc_2_41 loc_3_41 right)
        (next loc_2_41 loc_2_42 up)
        (next loc_2_41 loc_2_40 down)
        (next loc_3_41 loc_2_41 left)
        (next loc_3_41 loc_4_41 right)
        (next loc_3_41 loc_3_42 up)
        (next loc_3_41 loc_3_40 down)
        (next loc_4_41 loc_3_41 left)
        (next loc_4_41 loc_4_42 up)
        (next loc_4_41 loc_4_40 down)
        (next loc_2_42 loc_3_42 right)
        (next loc_2_42 loc_2_43 up)
        (next loc_2_42 loc_2_41 down)
        (next loc_3_42 loc_2_42 left)
        (next loc_3_42 loc_4_42 right)
        (next loc_3_42 loc_3_43 up)
        (next loc_3_42 loc_3_41 down)
        (next loc_4_42 loc_3_42 left)
        (next loc_4_42 loc_4_43 up)
        (next loc_4_42 loc_4_41 down)
        (next loc_2_43 loc_3_43 right)
        (next loc_2_43 loc_2_44 up)
        (next loc_2_43 loc_2_42 down)
        (next loc_3_43 loc_2_43 left)
        (next loc_3_43 loc_4_43 right)
        (next loc_3_43 loc_3_44 up)
        (next loc_3_43 loc_3_42 down)
        (next loc_4_43 loc_3_43 left)
        (next loc_4_43 loc_4_44 up)
        (next loc_4_43 loc_4_42 down)
        (next loc_2_44 loc_3_44 right)
        (next loc_2_44 loc_2_45 up)
        (next loc_2_44 loc_2_43 down)
        (next loc_3_44 loc_2_44 left)
        (next loc_3_44 loc_4_44 right)
        (next loc_3_44 loc_3_45 up)
        (next loc_3_44 loc_3_43 down)
        (next loc_4_44 loc_3_44 left)
        (next loc_4_44 loc_4_45 up)
        (next loc_4_44 loc_4_43 down)
        (next loc_2_45 loc_3_45 right)
        (next loc_2_45 loc_2_46 up)
        (next loc_2_45 loc_2_44 down)
        (next loc_3_45 loc_2_45 left)
        (next loc_3_45 loc_4_45 right)
        (next loc_3_45 loc_3_46 up)
        (next loc_3_45 loc_3_44 down)
        (next loc_4_45 loc_3_45 left)
        (next loc_4_45 loc_4_46 up)
        (next loc_4_45 loc_4_44 down)
        (next loc_2_46 loc_3_46 right)
        (next loc_2_46 loc_2_47 up)
        (next loc_2_46 loc_2_45 down)
        (next loc_3_46 loc_2_46 left)
        (next loc_3_46 loc_4_46 right)
        (next loc_3_46 loc_3_47 up)
        (next loc_3_46 loc_3_45 down)
        (next loc_4_46 loc_3_46 left)
        (next loc_4_46 loc_4_47 up)
        (next loc_4_46 loc_4_45 down)
        (next loc_2_47 loc_3_47 right)
        (next loc_2_47 loc_2_48 up)
        (next loc_2_47 loc_2_46 down)
        (next loc_3_47 loc_2_47 left)
        (next loc_3_47 loc_4_47 right)
        (next loc_3_47 loc_3_48 up)
        (next loc_3_47 loc_3_46 down)
        (next loc_4_47 loc_3_47 left)
        (next loc_4_47 loc_4_48 up)
        (next loc_4_47 loc_4_46 down)
        (next loc_2_48 loc_3_48 right)
        (next loc_2_48 loc_2_49 up)
        (next loc_2_48 loc_2_47 down)
        (next loc_3_48 loc_2_48 left)
        (next loc_3_48 loc_4_48 right)
        (next loc_3_48 loc_3_49 up)
        (next loc_3_48 loc_3_47 down)
        (next loc_4_48 loc_3_48 left)
        (next loc_4_48 loc_4_49 up)
        (next loc_4_48 loc_4_47 down)
        (next loc_2_49 loc_3_49 right)
        (next loc_2_49 loc_2_48 down)
        (next loc_3_49 loc_2_49 left)
        (next loc_3_49 loc_4_49 right)
        (next loc_3_49 loc_3_48 down)
        (next loc_4_49 loc_3_49 left)
        (next loc_4_49 loc_4_48 down)
        (patterned loc_2_2 blue)
        (patterned loc_4_2 pink)
        (patterned loc_2_5 pink)
        (patterned loc_4_5 blue)
        (patterned loc_2_6 red)
        (patterned loc_4_6 red)
    )

    (:goal
        (forall (?l - location)
            (not (exists (?p - pattern)
                (patterned ?l ?p)))))

    (:metric minimize (total-cost))
)
